package br.edu.ifsuldeminas.sd.chat.tela;

import br.edu.ifsuldeminas.sd.chat.ChatException;
import br.edu.ifsuldeminas.sd.chat.ChatFactory;
import br.edu.ifsuldeminas.sd.chat.MessageContainer;
import br.edu.ifsuldeminas.sd.chat.Sender;



public class Tela extends javax.swing.JFrame {
    
    private Sender sender;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConectar = new javax.swing.JButton();
        jFormattedTextFieldNome = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPortaLocal = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldPortaRemota = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaExibeMensagem = new javax.swing.JTextArea();
        jFormattedTextFieldDigitarMensagem = new javax.swing.JFormattedTextField();
        jButtonEnviar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chat UDP V2");
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(null);

        jButtonConectar.setBackground(new java.awt.Color(102, 255, 102));
        jButtonConectar.setText("Conectar");
        jButtonConectar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConectar);
        jButtonConectar.setBounds(800, 0, 90, 70);
        getContentPane().add(jFormattedTextFieldNome);
        jFormattedTextFieldNome.setBounds(450, 10, 120, 22);

        jFormattedTextFieldPortaLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPortaLocalActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldPortaLocal);
        jFormattedTextFieldPortaLocal.setBounds(450, 40, 120, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsuldeminas/sd/chat/imagem/fundooo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 370, 480);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nome:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 0, 50, 40);

        jFormattedTextFieldPortaRemota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPortaRemotaActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldPortaRemota);
        jFormattedTextFieldPortaRemota.setBounds(670, 10, 120, 22);

        jTextAreaExibeMensagem.setColumns(20);
        jTextAreaExibeMensagem.setRows(5);
        jScrollPane1.setViewportView(jTextAreaExibeMensagem);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 70, 520, 340);

        jFormattedTextFieldDigitarMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDigitarMensagemActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldDigitarMensagem);
        jFormattedTextFieldDigitarMensagem.setBounds(370, 410, 430, 70);

        jButtonEnviar.setBackground(new java.awt.Color(51, 153, 255));
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviar);
        jButtonEnviar.setBounds(800, 410, 90, 70);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Porta Remota:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(580, 10, 90, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Porta Local:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 40, 90, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarActionPerformed
        // TODO add your handling code here:
        String nome = jFormattedTextFieldNome.getText();
        int portaLocal = Integer.parseInt(jFormattedTextFieldPortaLocal.getText());
        int portaRemota = Integer.parseInt(jFormattedTextFieldPortaRemota.getText());

        try {
            sender = ChatFactory.build("localhost", portaRemota, portaLocal, new TelaContainer());
            jTextAreaExibeMensagem.append("Conectado com sucesso.\n");
        } catch (ChatException e) {
            jTextAreaExibeMensagem.append("Erro ao conectar: " + e.getMessage() + "\n");
        }
    }//GEN-LAST:event_jButtonConectarActionPerformed

    private void jFormattedTextFieldPortaLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPortaLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPortaLocalActionPerformed

    private void jFormattedTextFieldPortaRemotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPortaRemotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPortaRemotaActionPerformed

    private void jFormattedTextFieldDigitarMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDigitarMensagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDigitarMensagemActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        // TODO add your handling code here:
        String mensagem = jFormattedTextFieldDigitarMensagem.getText();
        String nome = jFormattedTextFieldNome.getText();
        if (!mensagem.isEmpty() && sender != null) {
            try {
                sender.send(mensagem + "::de::" + nome);
                jTextAreaExibeMensagem.append("[Você]: " + mensagem + "\n");
                jFormattedTextFieldDigitarMensagem.setText("");
            } catch (ChatException e) {
                jTextAreaExibeMensagem.append("Erro ao enviar mensagem: " + e.getMessage() + "\n");
            }
        }
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    private class TelaContainer implements MessageContainer {
        @Override
        public void newMessage(String message) {
            String[] messageParts = message.split(MessageContainer.FROM);
            String formattedMessage = "[" + messageParts[1] + "]: " + messageParts[0] + "\n";
            jTextAreaExibeMensagem.append(formattedMessage);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDigitarMensagem;
    private javax.swing.JFormattedTextField jFormattedTextFieldNome;
    private javax.swing.JFormattedTextField jFormattedTextFieldPortaLocal;
    private javax.swing.JFormattedTextField jFormattedTextFieldPortaRemota;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaExibeMensagem;
    // End of variables declaration//GEN-END:variables
}
